const { EmbedBuilder } = require("discord.js");
const {
  LEETCODE_FAVICON_URL,
  LEETCODE_BASE_URL,
  BOT_NAME,
} = require("./constants");

module.exports = {
  /**
   * embeds a leetcode problem into a discord embed
   * @param {Object} problem - the leetcode problem object
   * @param {string} title - the embed title
   * @returns {EmbedBuilder} the discord embed
   */
  embedProblem(problem, title) {
    const difficultyIcon = buildDifficultyIcon(problem.difficulty);
    const tags = buildTagsString(problem.tags);
    const reactions = buildReactionsString(problem.likes, problem.dislikes);

    return new EmbedBuilder()
      .setAuthor({ name: title, iconURL: LEETCODE_FAVICON_URL })
      .setURL(problem.url)
      .setTitle(`${problem.title} #${problem.id}`)
      .setColor(0xffd700)
      .setDescription(`${difficultyIcon}  ${problem.difficulty}`)
      .addFields({ name: "Tags", value: tags })
      .addFields({ name: "Reactions", value: reactions })
      .setFooter({ text: `generated by ${BOT_NAME}` })
      .setTimestamp();
  },
};

/**
 * builds the difficulty icon based on the difficulty
 * @param {string} difficulty - the problem difficulty
 * @returns {string} the difficulty icon
 */
function buildDifficultyIcon(difficulty) {
  difficulty = difficulty.toLowerCase();

  if (difficulty === "easy") {
    return ":green_square:";
  } else if (difficulty === "medium") {
    return ":orange_square:";
  } else {
    return ":red_square:";
  }
}

/**
 * builds a string of tags formatted for discord embed
 * @param {string[]} tags - array of tags
 * @returns the formatted tags string
 */
function buildTagsString(tags) {
  let tagsString = "";

  for (const tag of tags) {
    tagsString += `\`${tag}\` `;
  }

  return tagsString;
}

/**
 * builds a string of likes and dislikes formatted for discord embed
 * @param {number} likes - number of likes
 * @param {number} dislikes - number of dislikes
 * @returns the formatted reactions string
 */
function buildReactionsString(likes, dislikes) {
  return `\`👍 ${likes}\` \`👎 ${dislikes}\``;
}
