const { EmbedBuilder } = require("discord.js");

module.exports = {
  /**
   * embeds a leetcode problem into a discord embed
   * @param {Object} problem - the leetcode problem object
   * @returns {EmbedBuilder} the discord embed
   */
  embedProblem(problem) {
    const tagsString = buildTagsString(problem.tags);
    const difficultyIcon = buildDifficultyIcon(problem.difficulty);

    return new EmbedBuilder()
      .setURL(problem.url)
      .setTitle(`${problem.title} #${problem.id}`)
      .setColor(0xffd700)
      .setDescription(`${difficultyIcon}  ${problem.difficulty}`)
      .addFields({ name: "Tags", value: tagsString })
      .setFooter({ text: "generated by leet-bot" })
      .setTimestamp();
  },
};

/**
 * builds a string of tags formatted for discord embed
 * @param {string[]} tags - array of tags
 * @returns the formatted tags string
 */
function buildTagsString(tags) {
  let tagsString = "";

  for (const tag of tags) {
    tagsString += `\`${tag}\` `;
  }

  return tagsString;
}

/**
 * builds the difficulty icon based on the difficulty
 * @param {string} difficulty - the problem difficulty
 * @returns {string} the difficulty icon
 */
function buildDifficultyIcon(difficulty) {
  if (difficulty === "Easy") {
    return ":green_square:";
  } else if (difficulty === "Medium") {
    return ":orange_square:";
  } else {
    return ":red_square:";
  }
}
